### ISSUE TITLE
Vorschau funktioniert nicht mehr

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#102]
Wenn der Admin die Vorschau eines Restaurants aufruft, dann zeigt das System nur eine leere Seite an.
![Screenshot1](https://user-images.githubusercontent.com/71936375/100142424-25d9cb80-2e94-11eb-90e1-e16d00e1b486.png)

**Comment by marartz** [comment]
Habe ich im Feature-Branch GH-102 gefixt.

**Comment by jun71github** [comment]
Hi @marartz, hast du absichtlich den Text im Tooltip von "Vorschau" auf "Öffnen" geändert?
![grafik](https://user-images.githubusercontent.com/71936375/100795516-749cdd80-341f-11eb-8de7-d8e4496273ec.png)
Wenn ich die Vorschau öffne, dann klappt das System jetzt immer direkt den Warenkorb aus.

**Comment by marartz** [comment]
@jun71github : Ja, habe ich... Es ist praktisch ein Öffnen der Restaurantseite mit all der Funktionalität und keine Vorschau... Das Ausklappen ist auch in Ordnung. Passiert, wenn Du bereits etwas im Warenkorb hast.
