### ISSUE TITLE
Angabe der max. Zeichen „Name des Gerichts“ fehlerhaft

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#105]
Wenn der Restaurantadmin ein Restaurant bearbeitet, dabei im Bereich Speisekarte im Feld „Name des Gerichts“ mehr als 100 Zeichen eingibt, dann zeigt das System an, dass der Wert zu lang ist und kleiner/gleich 100 Zeichen sein muss. Soweit OK.
![Screenshot1](https://user-images.githubusercontent.com/71936375/100150301-b4077f00-2e9f-11eb-8af9-484fd9df4061.png)
Kürzt er nun den Wert auf 100 Zeichen, dann zeigt das System an, dass der max. Wert nun 20 Zeichen sei.
![Screenshot2](https://user-images.githubusercontent.com/71936375/100150334-bb2e8d00-2e9f-11eb-839e-5223faaab0aa.png)
Das ist auch der Wert den der Restaurantadmin speichern kann.

**Comment by marartz** [comment]
Im Branch GH-105 gefixt. Habe die Maximalzahl auf 30 gesetzt.

**Comment by jun71github** [comment]
Wenn ich mehr als 30 Zeichen eingebe, dann zeigt das System immer noch an, dass der max. Wert **100** Zeichen sind.
Es können jetzt 30 Zeichen gespeichert werden. --> Das ist OK.
