### ISSUE TITLE
Validierung bei der externen Speisekarte fehlerhaft

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#118]
Wenn der Restaurantadmin ein Restaurant bearbeitet, dabei im Bereich „Externe Speisekarte“ nicht alle Pflichtfelder ausgefüllt hat, die Speisekarte aber noch nicht aktiviert ist, dann zeigt das System trotzdem einen Validierungsfehler an.
![Was soll mir die Hinweismeldung sagen](https://user-images.githubusercontent.com/71936375/102270917-e5afbb00-3f1e-11eb-8d48-653d538e8824.png)

**Comment by jun71github** [comment]
- Wenn die externe Speisekarte nicht aktiviert ist und der Benutzer Änderungen an den drei Feldern (Name, Beschreibung und URL der Speisekarte) vornimmt, dann speichert das System die Änderungen nicht.
- Wenn der Benutzer die externe Speisekarte deaktivert, dann entfernt das System automatisch die Werte aus den drei Feldern

**Comment by marartz** [comment]
@jun71github : Das ist leider nicht anders möglich. Entweder ich speichere einen validen Datensatz oder ich lösche ihn. Das Deaktivieren, wie in der Oberfläche suggiert wird, ist mit dem aktuellen Datenmodell nicht möglich. Ist für jetzt in Ordnung. Soll aber in Zukunft verbessert werden.
