### ISSUE TITLE
Bereits existierende User mit Rolle Restaurantbetreiber können keinem zweiten Restaurant zugeordnet werden

### ISSUE THREAD

**Issue by annebeckmann** [marartz/FoodOrderSystem#119]
Beispiel: anne@coronahilfe-bocholt.de war vor der letzten Version schon dem Restaurant "Unterstützung Coronahilfe" in Rolle Restaurantverwalter zugeordnet. diesen User kann ich jetzt keinem weiteren Restaurant als Restaurantverwalter zuordnen. 
Dagegen probono@beckmann-beratung.de ist ein von mir in der aktuellen Version neu angelegter User ebenfalls mit Rolle Restaurantverwalter. Bei diesem User klappt das ohne Probleme.

![image](https://user-images.githubusercontent.com/76115904/102421432-af4c6b80-4004-11eb-9888-31d86e1ac5b1.png)
Beim Klick auf Speichern wird der Vorgang offenbar abgebrochen.

**Comment by marartz** [comment]
Meine Vermutung ist, dass hier das Autocomplete-Feature von Firefox/Chrome quergeschlagen hat. Wenn der Browser die Emailadresse automatisch einträgt, dann wird der Wert nicht korrekt hinzugefügt. Ich habe Autocomplete für das Feld jetzt ausgeschaltet. Sollte jetzt gehen.
