### ISSUE TITLE
Sonderöffnungszeiten anzeigen

### ISSUE THREAD

**Issue by annebeckmann** [marartz/FoodOrderSystem#120]
Sonderöffnungszeiten werden derzeit in Spalte AD der Restauranttabelle gepflegt im vorgeschlagenen Format:
DD.MM.YYYY: HH:MM-HH:MM; HH:MM-HH:MM; ... | DD.MM.YYYY: HH:MM-HH:MM; HH:MM-HH:MM; ... | ...
weitere Stati, die im Filter als geschlossen behandelt werden: geschlossen, ausgebucht

Beispiel:
24.12.2020: 10:00-14:00; 17:00-20:00 | 25.12.2020: 11:00-15:00 | 26.12.2020: geschlossen | 31.12.2020: 10:00-14:00 | 01.01.2021: ausgebucht

Anzeige:
![image](https://user-images.githubusercontent.com/76115904/102436241-68687100-4018-11eb-9fb3-14a35200af6e.png)
Sonderzeiten: 
24.12.2020: 10:00-14:00; 17:00-20:00
25.12.2020: 11:00-15:00
26.12.2020: geschlossen
31.12.2020: 10:00-14:00
01.01.2021: ausgebucht

**Comment by jun71github** [comment]
Meiner Meinung nach sollten wir die Sonderöffnungszeiten im eigenen Absatz snzeigen, dann sind sie presenter als jetzt
![Screenshot1](https://user-images.githubusercontent.com/71936375/102716800-6b948300-42de-11eb-9a65-aea2aaeded0d.png)
