### ISSUE TITLE
Hinzufügen-Button bei Sonderöffnungszeiten bleibt nach Auswahl des Datums ausgegraut

### ISSUE THREAD

**Issue by annebeckmann** [marartz/FoodOrderSystem#122]
![](https://i.imgur.com/7Im2Fxe.png)

**Comment by marartz** [comment]
@annebeckmann : Der Button ist nicht deaktiviert, das ist das Standarddesign von Buttons und ist bei jedem modalen Dialog so. Wenn das zu Mißverständnissen führt, müsste @lucawieczorek  vielleicht nochmals Hand anlegen.

**Comment by annebeckmann** [comment]
Muss nicht sein.
