### ISSUE TITLE
Mehrfaches Simulieren einer gleichnamigen (aber nicht inhaltsgleichen) Speisentabelle funktioniert nicht

### ISSUE THREAD

**Issue by annebeckmann** [marartz/FoodOrderSystem#126]
Häufige Situation beim Speisenimport ist, eine Simulation durchzuführen, festzustellen xyz ist noch falsch in der Importtabelle, den Import daraufhin NICHT durchzuführen, sondern die Tabelle erst zu korrigieren und neu zu speichern und dann die gleichnamige (aber inhaltlich veränderte) Tabelle nochmals zu simulieren. 
Das führt bei der gleichnamigen Tabelle leider dazu, dass eine zweite Simulation nicht mehr durchgeführt wird. Stattdessen kommt es zu einem technischen Fehler:
![](https://i.imgur.com/ZDkt1R1.png)
Erst das Aufrufen der Homepage und Neuaufrufen der Tabellen-Importfunktion erlaubt, dass die Tabelle erneut simuliert werden kann. (Das ist tatsächlich kein neuer Bug, den gibt es auch in der derzeitigen Version.)

**Comment by jun71github** [comment]
Nach jeder Simulation und Import muss die Importdatei neu ausgewählt werden. Dadurch kann der oben beschriebene Fehler nicht mehr auftreten. Gilt für Restaurant- / und Speisenimport.
