### ISSUE TITLE
Im Falle der Einstellung "Schicht", sollte während der Schicht auf Möglichkeit zur telefonischen Bestellung hingewiesen werden

### ISSUE THREAD

**Issue by annebeckmann** [marartz/FoodOrderSystem#127]
![](https://i.imgur.com/Te6Pm3b.png)

es sollte geändert/ergänzt werden: ...keine elektronischen Bestellungen für die jetzige Öffnungszeit entgegen, aber Du kannst jetzt entweder telefonisch für die aktuelle Öffnungszeit bestellen, oder elektronisch für eine spätere Öffnungszeit **vor**bestellen!

(Vielleicht kann man das auch noch knapper formulieren, aber so wie es da zur Zeit steht, klingt es so als könne man JETZT gar nicht elektronisch bestellen, aber man kann ja elektronisch bestellen, nur nicht für die aktuelle Öffnungszeit...)

**Comment by jun71github** [comment]
Passt, nur ein Punkt zu viel :)
![grafik](https://user-images.githubusercontent.com/71936375/102719944-49f0c700-42f1-11eb-8e24-2d2dd47fe2f8.png)
