### ISSUE TITLE
Löschung der Restaurant-GUID in /order-restaurant

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/FoodOrderSystem#31]
Beim Öffnen eines Restaurants in der Bestellung, aber auch in der Administration, werden aktuell Restaurants mit einer 36-stelligen ID geöffnet und nicht mit dem Namen des Restaurants.

Feature: Das System soll URLs verwenden, die den Restaurantnamen beinhalten.

**Comment by marartz** [comment]
@lucawieczorek : Was meinst Du damit?

**Comment by lucawieczorek** [comment]
Dass die URL dem Namen des Gastronoms entspricht

**Comment by jun71github** [comment]
@lucawieczorek: Ist in diesem Ticket dies gemeint?
![Screenshot1](https://user-images.githubusercontent.com/71936375/97363457-e921b100-18a2-11eb-88ca-fb2875dab052.png)
Wenn ja, dann scheint es OK zu sein...
