### ISSUE TITLE
"Passwort vergessen"-Funktion

### ISSUE THREAD

**Issue by marartz** [marartz/FoodOrderSystem#33]
Als Benutzer möchte ich die Möglichkeit haben, falls ich mein Passwort vergessen habe, dieses im System zurückzusetzen.

Akzeptanzkriterien:
- Es steht ein "Passwort vergessen"-Button im Anmeldedialog zur Verfügung, welcher auf den "Passwort vergessen"-Dialog leitet
- Der "Passwort vergessen"-Dialog erlaubt eine Emailadresse anzugeben und stellt einen Button zur Verfügung, ein neues Passwort anzufordern
- Der Benutzer erhält nach Klick auf den Button die Meldung, dass er in Kürze eine Email mit weiteren Anweisungen, zum Ändern seines Passwort, bekommt
- Beim Aufruf des Links, darf der Benutzer (nur) für diese Emailadresse ein neues Passwort vergeben
- Der Link ist maximal 30 Minuten gültig

**Comment by marartz** [comment]
@jun71github : Ich habe das Feature fertig implementiert... Wenn Du das testen willst, sag' kurz Bescheid, dann kann ich Dir erklären, wie das funktioniert... Ist auf einem Testsystem nicht ganz leicht zu testen. Und *wichtig*: Es befindet sich noch im Feature-Branch feature/gh-33.

**Comment by lucawieczorek** [comment]
@marartz wird ein Design für die E-Mail gebraucht?

**Comment by jun71github** [comment]
Hi @marartz , wenn ich in dem Feld "E-Mail-Adresse" irgendwelchen Blödsinn eingebe und den Button zum Passwort ändern klicke, dann fehlt dort die Validierung, ob das, was ich eingegeben habe, eine E-Mail-Adresse sein könnte.
![grafik](https://user-images.githubusercontent.com/71936375/100388457-f3160b80-302a-11eb-8abe-7cc294fda0e0.png)

**Comment by jun71github** [comment]
@marartz Nachdem ich mein richtige E-Mail-Adresse eingegeben habe, habe ich auch eine E-Mail bekommen, soweit OK. Aber wenn ich auf den Link in der E-Mail klicke, dann bekomme ich direkt diesen Hinweis.
![grafik](https://user-images.githubusercontent.com/71936375/100389356-7b95ab80-302d-11eb-9ad1-0ad876024203.png)
Zwischen Passwortanforderung und eingegangener E-Mail lag max. 1 Minute.
Danach habe ich nochmal die Passwortänderung angefordert. Jetzt kommt gar keine E-Mail mehr...

**Comment by jun71github** [comment]
Hi @marartz, ein paar Dinge sind mir gestern noch aufgefallen:
1. Tippfehler in der E-Mail
![001](https://user-images.githubusercontent.com/71936375/101932289-dd801480-3bda-11eb-8ac3-8aaf598b0b47.png)

2. Nachdem ich ein neues Passwort angefordert habe, erscheint im Browser ja dies hier:
![002](https://user-images.githubusercontent.com/71936375/101932471-1c15cf00-3bdb-11eb-8819-09ff7d0ea5e9.png)
Könntest du das evtl. so umbauen:
![002_edit](https://user-images.githubusercontent.com/71936375/101932532-3354bc80-3bdb-11eb-9d37-f1260de55e38.png)
... dann sieht der Benutzer direkt, wie er weitermachen kann. In dem bisherigen Design ist ja nichts mehr zu "klicken" vorhanden. OK, er kann ja auf das "X" im Bild klicken, aber ich bezweifle, dass der Benutzer das schnell findet.

3. Nach der Passwortänderung ist der Button für einige Zeit immer noch anklickbar. Dadurch kann der Eindruck entstehen, dass man nicht geklickt hat. Klickt der Benutzer also nochmal, dann schickt das System 2 E-Mails (oder mehr... :) )

**Comment by marartz** [comment]
@jun71github : Ich habe versucht, die gewünschten Änderungen einzubauen. Schau noch mal... Kannst Du im develop testen.

**Comment by jun71github** [comment]
@marartz: Schaut gut aus :)
Das Einzige, was noch fehlt ist dies hier:
![grafik](https://user-images.githubusercontent.com/71936375/102012583-89487200-3d4b-11eb-8ca3-9296fcd87aa3.png)
