### ISSUE TITLE
Restaurantsuche in order-home

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/FoodOrderSystem#35]
Suche der Restaurants in dem dafür vorgesehenem input-field.

**Comment by jun71github** [comment]
Sie Suche zeigt nicht alle Restaurants an, sondern nur die ersten 7 Ergebnisse. Das letzte Ergebnis ist unten abgeschnitten.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97756999-2e8ceb00-1afc-11eb-8722-71fea4225d9e.png)

**Comment by lucawieczorek** [comment]
@marartz Könntest du bitte einstellen, dass nur 6 Restaurants angezeigt werden?
