### ISSUE TITLE
Menübeschriftung fehlt

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#46]
Wenn ich mich nur als "Kunde" einlogge, dann fehlt die Menübeschriftung.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97229152-35ec8580-17d8-11eb-98a1-1f16175c20f1.png)

**Comment by marartz** [comment]
@jun71github : Login als Kunde ist momentan überhaupt nicht supported und muss auch nicht getestet werden.
