### ISSUE TITLE
Adminmenü nicht sichtbar

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#47]
Wenn der Benutzer sich 2 mal hintereinander einloggt, dann fehlt das Administrationsmenü komplett. Es ist erst nach Reload der Seite wieder vorhanden.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97229692-09853900-17d9-11eb-9c15-670ac02075cc.png)

STR´s:
- Button "Anmelden"
- Logindaten eingeben und anmelden
- Administration / Logout
- Logindaten eingeben und anmelden

Hinweis:
Der Anmelden Button funktioniert in diesen STR´s auch erst beim zweiten Klick.

**Comment by marartz** [comment]
@jun71github : kann ich mit den o.g. STRs nicht nachvollziehen... Schaust Du nochmals?

**Comment by jun71github** [comment]
@marartz: Jetzt ist der Fehler bei mir auch weg... :(
