### ISSUE TITLE
Warenkorb entfernen

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#49]
Wenn der Benutzer eingeloggt ist, Gerichte in den Warenkorb gelegt hat, diesen öffnet und sich abmeldet, dann zeigt das System noch immer den Begriff "Warenkorb" an. Dieser verschwindet, sobald man die Seite neu lädt oder drauf klickt.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97232379-523ef100-17dd-11eb-86eb-7003b7317359.png)

**Comment by lucawieczorek** [comment]
Aber das ist doch richtig so, oder verstehe ich das jetzt falsch?
