### ISSUE TITLE
Anmerkungen der Gerichte im Warenkorb (Variable)

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/FoodOrderSystem#54]

**Comment by marartz** [comment]
@lucawieczorek : Die Variable sollte "cartDish.getRemarks()" sein.

**Comment by lucawieczorek** [comment]
Alles klar, bin dabei!

**Comment by jun71github** [comment]
Die Anmerkung des Gerichts wird im Warenkorb nicht angezeigt.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97754766-6003b780-1af8-11eb-977c-ee2892d3b94e.png)

**Comment by lucawieczorek** [comment]
@marartz Variable ist zwar hinzugefügt, jedoch nicht sichtbar. Bitte schau dir das mal an...
