### ISSUE TITLE
Zahlungsmethodenauswahl im Checkout als Button

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/FoodOrderSystem#62]

**Comment by jun71github** [comment]
Funktion OK, aber eine Kleinigkeite noch. Wenn der Benutzer mit der Maus über die aktivierte Einstellung fährt, verschwindet der Haken. Das passiert auch in dem Bereich "Abholzeit".
![Screenshot1](https://user-images.githubusercontent.com/71936375/97777658-02ac4c80-1b72-11eb-8e66-a8a00210b8b7.png)
