### ISSUE TITLE
Lieferkosten vs Abholung im Warenkorb

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#67]
Wenn der Benutzer die Option "Abholung" (orderType=pickup) auswählt und den Warenkorb öffnet, dann zeigt das System im Warenkorb noch die Zeile "Lieferkosten" an.
Schöner wäre es, wenn der "Abholung" stehen würde.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97778280-89632880-1b76-11eb-91d3-d4e6b77a4428.png)

**Comment by jun71github** [comment]
Jetzt steht in der Zeile nur ein einzelnes €-Zeichen
![Screenshot3](https://user-images.githubusercontent.com/71936375/97783383-9c3a2500-1b97-11eb-8334-d93b020b5781.png)

**Comment by marartz** [comment]
Das habe ich gerade gefixt... Schau nochmal in der letzten Version nach.
