### ISSUE TITLE
Bestellbutton im Warenkorb nicht erreichbar

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#84]
Wenn der Benutzer so viel Speisen im Warenkorb hat, dass der Bestellbutton nach unten rausgeschoben ist, dann der Benutzer keine Chance die Bestellung fortzusetzen.
![Screenshot2](https://user-images.githubusercontent.com/71936375/98595053-c1d0d800-22d5-11eb-82bd-1249e83ab044.png)
Rauf- / Runterscrollen hilft hier nicht, da dadurch nur der Hintergrund scrollt.

**Comment by jun71github** [comment]
@lucawieczorek Es funktioniert zwar jetzt. Kannst du an dem Design der Scrollbar noch was machen? Die Optik der Scrollbar passt nicht so ganz zum Warenkorb.
![Screenshot2](https://user-images.githubusercontent.com/71936375/99286660-753b4e80-2839-11eb-859a-4eb30a662b03.png)

**Comment by lucawieczorek** [comment]
@jun71github Kümmere ich mich Freitag drum... Insofern ohne drittanbieter möglich

**Comment by jun71github** [comment]
@lucawieczorek Es funktioniert zwar jetzt. Kannst du an dem Design der Scrollbar noch was machen? Die Optik der Scrollbar passt nicht so ganz zum Warenkorb. Habe das mit dem develop Branch von heute getested...
