### ISSUE TITLE
Informationsdialog schließt sich nicht sofort

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#86]
Wenn der Benutzer den Informationsdialog öffnet, danach auf den Schließen Button oder auf das "X" klickt, schließt sich dieser nicht sofort. Der Benutzer muss hier 2mal klicken.
![Screenshot4](https://user-images.githubusercontent.com/71936375/98596130-48d28000-22d7-11eb-9d4a-ad7aecf42b9b.png)

**Comment by marartz** [comment]
@jun71github : Das Ticket ist jetzt mit Ende der Beta obsolet geworden... => Close.
