### ISSUE TITLE
Leere Seite, wenn Abholung deaktiviert

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#92]
Wenn der Restaurantadmin in seinem Restaurant die Bestellmöglichkeit „Abholung“ deaktiviert hat und ein Kunde in der Restaurantübersicht „Abholung“ aktiviert hat, dann zeigt das System dieses Restaurant trotzdem an. Klickt er nun auf das Restaurant, dann zeigt das System eine leere Seite an.
![Screenshot1](https://user-images.githubusercontent.com/71936375/99145909-2c399d80-2673-11eb-9181-8f4c0e35f4d9.png)

**Comment by marartz** [comment]
@jun71github : Abholung war vorher aktiviert, dann hat der Kunde das Restaurant mit Abholung gesucht, aber noch nicht aufgemacht, dann hat das Restaurant Abholung deaktiviert, dann hat der Kunde auf das Restaurant geklickt? Oder wie waren Deine STRs?

**Comment by jun71github** [comment]
@marartz Hier die STR´s:
-	Startseite aufrufen
-	Anmelden
-	Restaurants verwalten
-	Restaurant bearbeiten
-	Abholung deaktivieren
-	Speichern
-	Zurück zur Startseite
-	Alle anzeigen
-	Jetzt ist ja „Abholung“ direkt aktiviert
-	Bis zum Restaurant scrollen, wo Abholung deaktiviert ist
-	Das Restaurant sollte in der Liste ja eigentlich nicht auftauchen
-	Restaurant anklicken
