### ISSUE TITLE
Cookie-Einstellungsabfrage poppt immer wieder auf

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#93]
Ruft der Benutzer zum ersten Mal unsere Homepage auf, dann zeigt das System die Cookie-Einstellungen an, soweit OK. Speichert der Benutzer nun seine Einstellungen, wählt „Alle Ablehnen" oder „Alle Cookie akzeptieren“ und lädt die seine neu, dann poppt die Cookie-Einstellungsabfrage erneut auf.

**Comment by lucawieczorek** [comment]
Das liegt lediglich daran, dass das Banner nur auf der zugelassenen *.gastromio.de-Domain verfügbar ist.
