### ISSUE TITLE
Icons für den Seitenwechsel fehlen

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#96]
Auf den Seiten „Benutzerverwaltung“ und „Restaurantverwaltung“ fehlen die Icons für den Seitenwechsel.
![Screenshot1](https://user-images.githubusercontent.com/71936375/99299396-75dce080-284b-11eb-865a-912e4f7d5648.png)

**Comment by jun71github** [comment]
Im Bereich "Restaurantverwalter" fehlt auch das Icon.
![Screenshot2](https://user-images.githubusercontent.com/71936375/99300321-ba1cb080-284c-11eb-8100-1e82acd25e8d.png)

**Comment by jun71github** [comment]
Das + Icon um neue Speisen anzulegen fehlt auch.
![Screenshot1](https://user-images.githubusercontent.com/71936375/100544730-f9d59600-3257-11eb-9078-7e614123ed38.png)

**Comment by marartz** [comment]
@jun71github : Ist das noch ein Problem?
