### ISSUE TITLE
Zahlungsmethoden im Checkout nicht alphabetisch sortiert

### ISSUE THREAD

**Issue by jun71github** [marartz/FoodOrderSystem#97]
Im Checkout sind die Zahlungsmethoden nicht alphabetisch sortiert, in der Restaurantverwaltung hingegen schon.
![Screenshot1](https://user-images.githubusercontent.com/71936375/99303966-08807e00-2852-11eb-8ec5-18c793ed9f30.png)

**Comment by marartz** [comment]
Implementiert im Branch GH-97

**Comment by marartz** [comment]
Implementiert im Branch GH-97.
