### ISSUE TITLE
Wording bei geschlossenem Restaurant

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/FoodOrderSystem#98]
Wenn ein Restaurant einen kompletten Tag geschlossen hat, wird folgendes angezeigt.
![Bildschirmfoto 2020-11-22 um 11 08 51](https://user-images.githubusercontent.com/44336042/99900949-48f95500-2cb3-11eb-8a37-117902191d73.png)

**Comment by jun71github** [comment]
@marartz Der eigentliche Fehler ist nun behoben. Wenn das Restaurant aber immer unterschiedliche Öfnungszeiten hat, sieht das so aus:
![Screenshot1](https://user-images.githubusercontent.com/71936375/100131660-9ed12700-2e84-11eb-9a03-ccab5c0713bc.png)
Sollen wir das "von" entfernen, was meinst du?
